export enum ExecutionJobStatus {
  QUEUED = 'QUEUED',
  READY = 'READY',
  RUNNING = 'RUNNING',
  FINISHED_WITH_SUCCESS = 'FINISHED_WITH_SUCCESS',
  FINISHED_WITH_ERROR = 'FINISHED_WITH_ERROR',
  FAILED = 'FAILED',
}
